---
- name: Restart awg-quick
  ansible.builtin.systemd:
    name: awg-quick@awg0
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart amnezia-auth
  ansible.builtin.systemd:
    name: amnezia-auth
    state: restarted

- name: Restart amnezia-daemon
  ansible.builtin.systemd:
    name: amnezia-daemon
    state: restarted
