---
- name: Import installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import VPN tasks
  ansible.builtin.import_tasks: vpn.yml

- name: Import iptables tasks
  ansible.builtin.import_tasks: iptables.yml

- name: Import users tasks
  ansible.builtin.import_tasks: users.yml

- name: Import application tasks
  ansible.builtin.import_tasks: app.yml

- name: Import systemd tasks
  ansible.builtin.import_tasks: systemd.yml

- name: Import security tasks
  ansible.builtin.import_tasks: security.yml

- name: Import client configuration tasks
  ansible.builtin.import_tasks: client_configs.yml
